### PR TITLE
JENKINS-50046: set the parse interval, JENKINS-50048: progress bar

### PR DESCRIPTION
**Pull request by dcendents**
Hi,

This pull request implements two new features:

https://issues.jenkins-ci.org/browse/JENKINS-50046: In pipeline projects it is possible to set the parse interval to a fixed value. When it is not set or for Freestyle projects the current logic is kept (every 1/100 of the estimated build time and never more often than every 5 seconds).

image

https://issues.jenkins-ci.org/browse/JENKINS-50048: Adding a progress bar to the summary view. The tooltip shows the number of completed tests vs expected tests and the estimated remaining time. This is based on the latest test results from previous builds.

New project (or cannot find previous test results):
image

Progress with tooltip:
image

### CODE REVIEW

**Comment by jglick** [comment]
> This pull request implements two new features

Generally best to split into two PRs then.

I have contributed to this plugin in the past but I am not sure if it has a maintainer currently. Are you interested in adopting it?

**Comment by dcendents** [comment]
@jglick 

Yes I like to adopt it, I've been contributing to a lot of plugins already it's probably time I get involved a bit more with all the release lifecycle.

The plugin is not marked for adoption, do I still go through with the procedure here: https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/ ?

**Comment by jglick** [comment]
Yes. https://github.com/jenkinsci/junit-realtime-test-reporter-plugin/commit/cbd19bb6c3920f6f4a0cb4f524f3265cf80ab1ae suggests it is unmaintained, as does https://github.com/jenkins-infra/repository-permissions-updater/blob/db153f3cde58b13b9b31e8c8a0732114f2307272/permissions/plugin-junit-realtime-test-reporter.yml#L6.

**Comment by timja** [comment]
Please split into 2 PRs and resolve the conflicts.

Both are likely fine but the PR is a bit big right now.

**Comment by dcendents** [comment]
Closing in favor of #32 and #33

**Pull request closed without merging**
