### PR TITLE
Handle broken connections

### PR DESCRIPTION
**Pull request by jglick**
I encountered a case where a build ran for an hour and a half, collecting realtime test results, and then bombed out apparently due to a broken Remoting connection. Unfortunately the build then wound up with _no_ test results, since the realtime results had been deleted when the block closed, and the regular archiving failed:

```
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2638)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3113)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:853)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:349)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:59)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:73)
Caused: hudson.remoting.ChannelClosedException: Remote call on … failed. The channel is closing down or has closed down
	at hudson.remoting.Channel.call(Channel.java:897)
	at hudson.FilePath.act(FilePath.java:987)
Caused: java.io.IOException: remote file operation failed: … at hudson.remoting.Channel@…
	at hudson.FilePath.act(FilePath.java:994)
	at hudson.FilePath.act(FilePath.java:976)
	at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:103)
	at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:128)
	at hudson.tasks.junit.JUnitResultArchiver.perform(JUnitResultArchiver.java:149)
	at org.jenkinsci.plugins.junitrealtimetestreporter.RealtimeJUnitStep$Callback.finished(RealtimeJUnitStep.java:166)
	at org.jenkinsci.plugins.workflow.steps.BodyExecutionCallback$TailCall.onFailure(BodyExecutionCallback.java:124)
	at …
```

Thus the only information about test failures was some messages in the log, which of course is tricky to read and omits stdio etc.

This patch ensures that we will record whatever test results we had.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
Note that this will only be “checkpointing” test results from the last point that a human looked at them (or at least that parsing was forced for some reason, for example by visiting the build index page). Better than nothing, but ideally the plugin would automatically gather results in the background at intervals. That would also solve the problem mentioned in a TODO comment that currently the UI blocks making agent connections, which can be quite slow, especially if you have many `parallel` branches and a laggy network.

**Comment by jglick** [comment]
@reviewbybees done

**Comment by olivergondza** [comment]
> ... but ideally the plugin would automatically gather results in the background at intervals. That would also solve the problem mentioned in a TODO comment that currently the UI blocks making agent connections, which can be quite slow, especially if you have many parallel branches and a laggy network.

That would introduce the realtime overhead even when nobody is looking at the results but I see your point.

**Comment by jglick** [comment]
> That would introduce the realtime overhead even when nobody is looking at the results

Yes, it would, but I think that is less of a problem than the current behavior.

**Pull request merged**
